"""
AWS SNS MCP Server.

Exposes alerting tools with Teams-to-SNS failover over the
Model Context Protocol.
Transport: streamable-http (for AgentCore Runtime hosting).
"""

from __future__ import annotations

import json
import os

import boto3
from botocore.exceptions import ClientError
from mcp.server.fastmcp import FastMCP

from tools import send_alert_with_failover, request_approval, check_approval_status, update_approval_status
from aws_helpers import setup_logging

logger = setup_logging("mcp-server.sns")

# ── Required env vars for approval workflow ──────────────────────────────

_APPROVAL_ENV_KEYS = (
    "APPROVALS_TABLE",
    "APPROVAL_API_URL",
    "SCHEDULER_ROLE_ARN",
    "APPROVAL_HANDLER_ARN",
    "SNS_TOPIC_ARN",
)

_RUNNER_STACK = "DevOpsAgent-Runner"
_REGION = os.environ.get("AWS_REGION", "ap-southeast-2")


def _cfn_outputs(stack_name: str) -> dict[str, str]:
    """Return CloudFormation stack outputs as {OutputKey: OutputValue}."""
    try:
        cfn = boto3.client("cloudformation", region_name=_REGION)
        resp = cfn.describe_stacks(StackName=stack_name)
        outputs = resp["Stacks"][0].get("Outputs", [])
        return {o["OutputKey"]: o["OutputValue"] for o in outputs}
    except Exception as exc:
        logger.warning("Could not fetch CloudFormation outputs for %s: %s", stack_name, exc)
        return {}


def _resolve_approval_env() -> None:
    """Ensure all approval env vars are set, auto-resolving from CloudFormation
    and AWS APIs.

    APPROVAL_API_URL is ALWAYS re-fetched from CloudFormation because the
    API Gateway URL changes whenever the DevOpsAgent-Runner stack is
    deleted and recreated (new API Gateway ID is generated by CDK).
    All other values are stable and only resolved when missing.
    """
    logger.info("Resolving approval infrastructure config from CloudFormation …")
    cfn = _cfn_outputs(_RUNNER_STACK)

    # ── APPROVAL_API_URL: always override from CloudFormation ────────────
    # This is the only value that can silently change on CDK redeploy.
    if "ApprovalApiUrl" in cfn:
        fresh_url = cfn["ApprovalApiUrl"].rstrip("/")
        current_url = os.environ.get("APPROVAL_API_URL", "").rstrip("/")
        if fresh_url != current_url:
            logger.warning(
                "APPROVAL_API_URL mismatch — Dockerfile=%r  CloudFormation=%r — using CloudFormation",
                current_url or "(not set)", fresh_url,
            )
        os.environ["APPROVAL_API_URL"] = fresh_url
        logger.info("APPROVAL_API_URL = %s", fresh_url)
    else:
        logger.error("ApprovalApiUrl not found in CloudFormation stack %s", _RUNNER_STACK)

    # ── Remaining vars: only resolve when missing ────────────────────────
    cfn_fallbacks = {
        "ApprovalsTableName": "APPROVALS_TABLE",
        "SnsTopicArn":        "SNS_TOPIC_ARN",
    }
    for cfn_key, env_key in cfn_fallbacks.items():
        if not os.environ.get(env_key, "").strip() and cfn_key in cfn:
            os.environ[env_key] = cfn[cfn_key]
            logger.info("Resolved %s = %s", env_key, os.environ[env_key])

    # Approval Handler Lambda ARN
    if not os.environ.get("APPROVAL_HANDLER_ARN", "").strip():
        try:
            lm = boto3.client("lambda", region_name=_REGION)
            fn = lm.get_function(FunctionName="devops-agent-approval-handler")
            os.environ["APPROVAL_HANDLER_ARN"] = fn["Configuration"]["FunctionArn"]
            logger.info("Resolved APPROVAL_HANDLER_ARN = %s", os.environ["APPROVAL_HANDLER_ARN"])
        except ClientError as exc:
            logger.error("Could not resolve APPROVAL_HANDLER_ARN: %s", exc)

    # Scheduler IAM Role ARN
    if not os.environ.get("SCHEDULER_ROLE_ARN", "").strip():
        try:
            iam = boto3.client("iam", region_name=_REGION)
            role = iam.get_role(RoleName="devops-agent-scheduler-invoke-role")
            os.environ["SCHEDULER_ROLE_ARN"] = role["Role"]["Arn"]
            logger.info("Resolved SCHEDULER_ROLE_ARN = %s", os.environ["SCHEDULER_ROLE_ARN"])
        except ClientError as exc:
            logger.error("Could not resolve SCHEDULER_ROLE_ARN: %s", exc)

    # Final check
    still_missing = [k for k in _APPROVAL_ENV_KEYS if not os.environ.get(k, "").strip()]
    if still_missing:
        logger.warning("Approval env vars still unresolved after auto-resolve: %s", still_missing)
    else:
        logger.info("All approval env vars resolved successfully")


# ── Log current approval config at startup ───────────────────────────────

def _log_startup_config() -> None:
    logger.info("SNS MCP Server starting — approval config:")
    for key in _APPROVAL_ENV_KEYS:
        val = os.environ.get(key, "")
        if val:
            # Truncate long ARNs/URLs for readability
            display = val if len(val) <= 60 else val[:57] + "..."
            logger.info("  %s = %s", key, display)
        else:
            logger.error("  %s = *** NOT SET ***", key)


# ── Server setup ─────────────────────────────────────────────────────────

mcp = FastMCP("sns-server", host="0.0.0.0", stateless_http=True)

# ── Tool registrations ───────────────────────────────────────────────────


@mcp.tool()
async def send_alert_with_failover_tool(subject: str, message: str) -> str:
    """Send an alert to Teams; if Teams is unavailable, fail over to AWS SNS.
    Returns which channel was used or whether both failed.
    """
    result = await send_alert_with_failover(
        subject=subject,
        message=message,
    )
    return json.dumps(result, indent=2, default=str)


@mcp.tool()
async def request_approval_tool(
    instance_id: str,
    action_type: str,
    reason: str,
    details: str = "",
) -> str:
    """Request human approval for a remediation action via email with
    clickable APPROVE/REJECT links. Supported action_types: restart,
    disk_cleanup, kill_process, cache_clear.
    """
    result = await request_approval(
        instance_id=instance_id,
        action_type=action_type,
        reason=reason,
        details=details,
    )
    return json.dumps(result, indent=2, default=str)


@mcp.tool()
async def check_approval_status_tool(approval_id: str) -> str:
    """Check the current status of an approval request.
    Returns the approval details including status (pending/approved/rejected/executed),
    instance_id, action_type, reason, and details.
    Use this to verify an approval before executing the approved action.
    """
    result = await check_approval_status(approval_id=approval_id)
    return json.dumps(result, indent=2, default=str)


@mcp.tool()
async def update_approval_status_tool(approval_id: str, status: str) -> str:
    """Update the status of an approval request after execution.
    Call this after executing an approved action to mark it as 'executed',
    or 'failed' if the execution failed.
    """
    result = await update_approval_status(approval_id=approval_id, status=status)
    return json.dumps(result, indent=2, default=str)


# ── Entry point ──────────────────────────────────────────────────────────


def main() -> None:
    """Run the MCP server over streamable-http transport."""
    # Ensure approval infrastructure env vars are set before serving
    _resolve_approval_env()
    _log_startup_config()

    logger.info("Starting SNS MCP server (streamable-http) …")
    mcp.run(transport="streamable-http")


if __name__ == "__main__":
    main()
 